default['mysql']['db']['user'] = 'saji'
default['mysql']['db']['pass'] = 'saji'
default['mysql']['db']['database'] = 'bbbs'
default['mysql']['db']['host'] = 'localhost'
default['mysql']['db']['rootpass'] = ''