CREATE TABLE nations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) unique
);

CREATE TABLE products (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    nation_id INT,
    description TEXT DEFAULT NULL,
    link VARCHAR(255) DEFAULT NULL,
    imagename VARCHAR(50) DEFAULT NULL,
    created DATETIME DEFAULT NULL,
    modified DATETIME DEFAULT NULL
);
