CREATE TABLE nations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) unique
);

CREATE TABLE products (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    nation_id INT,
    image_id INT DEFAULT NULL,
    description TEXT DEFAULT NULL,
    link VARCHAR(255) DEFAULT NULL,
    created DATETIME DEFAULT NULL,
    modified DATETIME DEFAULT NULL
);

CREATE TABLE images (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  filepath VARCHAR(60) UNIQUE NOT NULL,
  size  INT NOT NULL,
  type VARCHAR(20) NOT NULL
);